import React, { useState } from "react";
import { FullAppState, SymbolType, TradingSignal, RetestCandidate } from "../types";
import { Search, Filter, RefreshCw, BarChart2, CheckCircle2, AlertTriangle, ChevronDown, ChevronUp, Sparkles, Sliders } from "lucide-react";

interface SignalsViewProps {
  state: FullAppState;
  onRefresh: () => void;
  activeSubMenu?: string;
  onSwitchSubMenu?: (menu: string) => void;
}

export default function SignalsView({ 
  state, 
  onRefresh, 
  activeSubMenu = "all", 
  onSwitchSubMenu 
}: SignalsViewProps) {
  const [selectedSymbol, setSelectedSymbol] = useState<string>("ALL");
  const [selectedStatus, setSelectedStatus] = useState<string>("ALL");
  const [selectedRegime, setSelectedRegime] = useState<string>("ALL");
  const [isPolling, setIsPolling] = useState(false);
  const [showSuccessToast, setShowSuccessToast] = useState(false);
  const [expandedSignalId, setExpandedSignalId] = useState<string | null>(null);

  const handlePollSignals = async () => {
    if (isPolling) return;
    setIsPolling(true);
    try {
      await onRefresh();
      setShowSuccessToast(true);
      setTimeout(() => {
        setShowSuccessToast(false);
      }, 4000);
    } catch (err) {
      console.error("Polled signals failed:", err);
    } finally {
      setIsPolling(false);
    }
  };

  const filteredSignals = state.signals.filter((s) => {
    const symbolMatch = selectedSymbol === "ALL" || s.symbol === selectedSymbol;
    const statusMatch = selectedStatus === "ALL" || s.status === selectedStatus;
    const regimeMatch = selectedRegime === "ALL" || s.regime === selectedRegime;
    return symbolMatch && statusMatch && regimeMatch;
  });

  const getStatusStyle = (status: string) => {
    switch (status) {
      case "EXECUTED":
        return "bg-emerald-500/10 text-emerald-400 border border-emerald-500/15";
      case "BLOCKED":
        return "bg-rose-500/10 text-rose-400 border border-rose-500/15";
      case "PENDING_RETEST":
        return "bg-amber-500/10 text-amber-400 border border-amber-500/15 animate-pulse";
      default:
        return "bg-zinc-800 text-zinc-400 border border-zinc-700/30";
    }
  };

  const formatPrice = (symbol: string, val: number | undefined) => {
    if (val === undefined || val === null) return "N/A";
    let decimals = 2;
    const s = symbol.toUpperCase();
    if (s.includes("JPY")) {
      decimals = 2;
    } else if (s.includes("USD") && (s.startsWith("EUR") || s.startsWith("GBP") || s.startsWith("AUD") || s.startsWith("NZD") || s.startsWith("CAD") || s.startsWith("CHF") || s.startsWith("USD"))) {
      decimals = 4;
    }
    return `$${val.toLocaleString(undefined, { minimumFractionDigits: decimals, maximumFractionDigits: decimals })}`;
  };

  const uniqueSymbols = [
    "EURUSD", "GBPUSD", "USDJPY", "AUDUSD",
    "BTCUSD", "ETHUSD", "SOLUSD", "BNBUSD",
    "AAPL", "TSLA", "MSFT", "NVDA",
    "XAUUSD", "USOIL", "XAGUSD", "NGAS",
    "SPX500", "NDX100", "DJI30", "GER40"
  ];
  const uniqueRegimes = ["TRENDING_BULL", "TRENDING_BEAR", "RANGING_CHOP", "ACCUMULATION"];

  const activeRetestCount = state.retestCandidates
    ? state.retestCandidates.filter(c => c.status === "WAITING_CANDLE_CLOSE" || c.status === "WAITING_RETEST").length
    : 0;

  return (
    <div className="space-y-5">
      {showSuccessToast && (
        <div id="signals-success-toast" className="fixed top-5 right-5 z-50 flex items-center gap-2 px-4 py-3 bg-zinc-900 border border-emerald-500/30 text-emerald-400 text-xs font-semibold rounded-xl shadow-lg transition-all animate-in fade-in slide-in-from-top-4 duration-300">
          <CheckCircle2 className="h-4 w-4 text-emerald-400 animate-bounce" />
          <span>Active signal detectors polling executed successfully! Market filters up to date.</span>
        </div>
      )}

      <div className="flex flex-col md:flex-row md:items-center md:justify-between border-b border-zinc-900 pb-4 gap-4">
        <div>
          <h3 className="font-display text-lg font-black text-white flex items-center gap-2">
            <BarChart2 className="h-5 w-5 text-emerald-500" />
            Detector Signal History Ledger
          </h3>
          <p className="text-xs text-zinc-400 mt-1">
            Browse complete list of algorithmic triggers generated by active strategy detectors, with block tracking analytics.
          </p>
        </div>
        <button
          onClick={handlePollSignals}
          disabled={isPolling}
          className={`flex items-center justify-center gap-1.5 px-3 py-2 rounded-lg text-xs font-semibold border transition-all cursor-pointer ${
            isPolling 
              ? "bg-zinc-800 border-zinc-700 text-zinc-500 cursor-not-allowed" 
              : "bg-zinc-900 hover:bg-zinc-800 text-zinc-350 hover:text-white border-zinc-800 self-start md:self-auto"
          }`}
        >
          <RefreshCw className={`h-3.5 w-3.5 ${isPolling ? "animate-spin text-zinc-500" : ""}`} />
          {isPolling ? "Polling Strategy Detectors..." : "Poll Active Signals"}
        </button>
      </div>

      {/* Dynamic Filters Panel & Ledger List */}
      <div className="rounded-xl border border-zinc-900 bg-zinc-950/40 p-4 flex flex-wrap gap-4 items-center justify-between">
        <div className="flex flex-wrap gap-2.5 items-center">
          <div className="flex items-center gap-1 text-[11px] text-zinc-400 mr-2 uppercase tracking-wider font-semibold">
            <Filter className="h-3.5 w-3.5" /> Filter Signals:
          </div>

              {/* Symbol Selector */}
              <select
                value={selectedSymbol}
                onChange={(e) => setSelectedSymbol(e.target.value)}
                className="rounded-lg border border-zinc-800 bg-zinc-900/60 px-3 py-1.5 text-xs text-zinc-200 outline-none hover:border-zinc-700 focus:border-zinc-650 font-mono"
              >
                <option value="ALL">All Trading Pairs</option>
                {uniqueSymbols.map((s) => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>

              {/* Status selector */}
              <select
                value={selectedStatus}
                onChange={(e) => setSelectedStatus(e.target.value)}
                className="rounded-lg border border-zinc-800 bg-zinc-900/60 px-3 py-1.5 text-xs text-zinc-200 outline-none hover:border-zinc-700 focus:border-zinc-650 font-mono"
              >
                <option value="ALL">All Resolutions (Executed / Blocked)</option>
                <option value="EXECUTED">EXECUTED Only</option>
                <option value="BLOCKED">BLOCKED Only</option>
              </select>

              {/* Regime Selector */}
              <select
                value={selectedRegime}
                onChange={(e) => setSelectedRegime(e.target.value)}
                className="rounded-lg border border-zinc-800 bg-zinc-900/60 px-3 py-1.5 text-xs text-zinc-200 outline-none hover:border-zinc-700 focus:border-zinc-650 font-mono"
              >
                <option value="ALL">All Market Regimes</option>
                {uniqueRegimes.map((reg) => (
                  <option key={reg} value={reg}>{reg}</option>
                ))}
              </select>
            </div>

            <div className="text-xs text-zinc-550 font-bold">
              Found <span className="text-zinc-200 font-mono">{filteredSignals.length}</span> recorded signals
            </div>
          </div>

          {/* List content */}
          <div className="rounded-xl border border-zinc-900 bg-zinc-950/20 overflow-hidden">
            {filteredSignals.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-16 text-center">
                <Search className="h-10 w-10 text-zinc-800 mb-3 animate-pulse" />
                <h4 className="text-sm font-semibold text-zinc-400">No signals found</h4>
                <p className="text-xs text-zinc-500 max-w-sm mt-1 leading-normal">
                  No matching mathematical patterns evaluated. Make sure your Auto-Trader is active.
                </p>
              </div>
            ) : (
              <div className="overflow-x-auto">
                <table className="w-full text-left border-collapse">
                  <thead>
                    <tr className="border-b border-zinc-900 bg-zinc-950/60 font-display text-xs font-semibold text-zinc-400 whitespace-nowrap">
                      <th className="py-3 px-4">Signal ID</th>
                      <th className="py-3 px-4">Trigger Time</th>
                      <th className="py-3 px-4">Symbol</th>
                      <th className="py-3 px-4">Action Type</th>
                      <th className="py-3 px-4">Entry level</th>
                      <th className="py-3 px-4">Stop Loss / Take Profit</th>
                      <th className="py-3 px-4">Timeframe</th>
                      <th className="py-3 px-4">Market Regime</th>
                      <th className="py-3 px-4">Strategy Source</th>
                      <th className="py-3 px-4 text-center">Resolution</th>
                      <th className="py-3 px-4">Status / Blocked Reason</th>
                      <th className="py-3 px-4 text-right">Details</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-zinc-900 font-mono text-xs">
                    {filteredSignals.map((sig) => {
                      const isExpanded = expandedSignalId === sig.id;

                      return (
                        <React.Fragment key={sig.id}>
                          <tr 
                            className={`hover:bg-zinc-900/10 transition-colors cursor-pointer whitespace-nowrap ${isExpanded ? "bg-zinc-900/5" : ""}`}
                            onClick={() => setExpandedSignalId(isExpanded ? null : sig.id)}
                          >
                            <td className="py-4 px-4 text-zinc-500 font-bold truncate max-w-[90px]" title={sig.id}>
                              {sig.id}
                            </td>
                            <td className="py-4 px-4 text-zinc-400 font-sans">
                              {new Date(sig.time).toLocaleTimeString()}
                            </td>
                            <td className="py-4 px-4 font-bold text-white">{sig.symbol}</td>
                            <td className="py-4 px-4">
                              <span
                                className={`inline-block font-bold text-[10px] px-2 py-0.5 rounded-sm ${
                                  sig.type === "BUY" ? "bg-emerald-500/15 text-emerald-400" : sig.type === "SELL" ? "bg-rose-500/15 text-rose-400" : "bg-zinc-800 text-zinc-400"
                                }`}
                              >
                                {sig.type}
                              </span>
                            </td>
                            <td className="py-4 px-4 font-bold text-zinc-200">
                              {formatPrice(sig.symbol, sig.price)}
                            </td>
                            <td className="py-4 px-4 text-zinc-400 text-[10.5px] leading-relaxed">
                              <div className="flex flex-col gap-0.5 font-mono">
                                <div><span className="text-rose-400 font-bold mr-1">SL:</span>{formatPrice(sig.symbol, sig.stopLoss)}</div>
                                <div><span className="text-emerald-400 font-bold mr-1">TP:</span>{formatPrice(sig.symbol, sig.takeProfit)}</div>
                                {(sig.tp1 || sig.tp2 || sig.tp3) && (
                                  <div className="text-[9.5px] text-zinc-500 font-mono mt-0.5 border-t border-zinc-900/40 pt-0.5 flex flex-wrap gap-x-2">
                                    {sig.tp1 && <span>T1: {formatPrice(sig.symbol, sig.tp1)}</span>}
                                    {sig.tp2 && <span>T2: {formatPrice(sig.symbol, sig.tp2)}</span>}
                                    {sig.tp3 && <span>T3: {formatPrice(sig.symbol, sig.tp3)}</span>}
                                  </div>
                                )}
                              </div>
                            </td>
                            <td className="py-4 px-4">
                              <span className="text-[10px] uppercase font-bold text-zinc-400 bg-zinc-900 border border-zinc-800 px-1.5 py-0.5 rounded">
                                {sig.timeframe}
                              </span>
                            </td>
                            <td className="py-4 px-4 font-sans text-xs">
                              <span className={`inline-flex px-1.5 py-0.5 rounded text-[10px] font-bold ${
                                sig.regime === "TRENDING_BULL" ? "bg-emerald-500/10 text-emerald-400" :
                                sig.regime === "TRENDING_BEAR" ? "bg-rose-500/10 text-rose-400" :
                                sig.regime === "ACCUMULATION" ? "bg-purple-500/10 text-purple-400" :
                                "bg-amber-500/10 text-amber-400"
                              }`}>
                                {sig.regime}
                              </span>
                            </td>
                            <td className="py-4 px-4 font-sans font-medium text-zinc-350">{sig.strategyName}</td>
                            <td className="py-4 px-4 text-center">
                              <span className={`inline-block text-[9px] font-black px-2 py-0.5 rounded uppercase ${getStatusStyle(sig.status)}`}>
                                {sig.status}
                              </span>
                            </td>
                            <td className="py-4 px-4 font-sans text-xs">
                              {sig.status === "EXECUTED" ? (
                                <span className="text-emerald-400 font-bold flex items-center gap-1">
                                  <CheckCircle2 className="h-3.5 w-3.5" /> Position Created
                                </span>
                              ) : (
                                <span className="text-rose-400 font-bold flex items-center gap-1.5 bg-rose-500/5 px-2 py-1 border border-rose-500/10 rounded">
                                  <AlertTriangle className="h-3.5 w-3.5 text-rose-400 shrink-0" />
                                  Blocked ({sig.blockedReason})
                                </span>
                              )}
                            </td>
                            <td className="py-4 px-4 text-right">
                              <button 
                                className="bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 p-1 rounded transition-colors text-zinc-400 cursor-pointer"
                                onClick={(e) => {
                                  e.stopPropagation();
                                  setExpandedSignalId(isExpanded ? null : sig.id);
                                }}
                              >
                                {isExpanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
                              </button>
                            </td>
                          </tr>

                          {isExpanded && (
                            <tr className="bg-zinc-950/60 border-y border-zinc-900/85">
                              <td colSpan={12} className="p-5 font-sans whitespace-normal">
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                                  <div className="space-y-3.5">
                                    <div className="flex items-center gap-2">
                                      <Sparkles className="h-4 w-4 text-emerald-400" />
                                      <span className="text-xs font-bold text-white uppercase tracking-wider">Strategic Thesis Details</span>
                                    </div>
                                    <div className="bg-zinc-950/80 rounded-lg p-4 border border-zinc-900 font-mono text-xs text-zinc-350 leading-relaxed">
                                      Setup was triggered by mathematical indicators of strategy <strong>{sig.strategyName}</strong> on asset <strong>{sig.symbol}</strong>, validated under active regime <strong>{sig.regime}</strong> on <strong>{sig.timeframe}</strong> timeframe. Logged entry trigger level was {formatPrice(sig.symbol, sig.price)}.
                                    </div>
                                  </div>
                                  <div className="space-y-4 font-mono text-xs text-zinc-400">
                                    <div className="flex items-center gap-2">
                                        <Sliders className="h-4 w-4 text-sky-400" />
                                      <span className="text-xs font-bold text-white uppercase tracking-wider font-sans">Execution Properties</span>
                                    </div>
                                    <div className="grid grid-cols-2 gap-4">
                                      <div className="bg-zinc-950/40 rounded-lg p-3 border border-zinc-900/50">
                                        <span className="text-[10px] text-zinc-500 uppercase tracking-wider block font-bold font-mono">Bar Timestamp</span>
                                        <span className="text-xs text-zinc-300 font-mono mt-1 block">{sig.barTime || "N/A"}</span>
                                      </div>
                                      <div className="bg-zinc-950/40 rounded-lg p-3 border border-zinc-900/50">
                                        <span className="text-[10px] text-zinc-500 uppercase tracking-wider block font-bold font-mono">Strategy Identifier</span>
                                        <span className="text-xs text-zinc-300 font-mono mt-1 block">{sig.strategyId}</span>
                                      </div>
                                      <div className="bg-zinc-950/40 rounded-lg p-3 border border-zinc-900/50">
                                        <span className="text-[10px] text-zinc-500 uppercase tracking-wider block font-bold font-mono">Setup Price</span>
                                        <span className="text-xs text-zinc-300 font-mono mt-1 block">{formatPrice(sig.symbol, sig.price)}</span>
                                      </div>
                                      <div className="bg-zinc-950/40 rounded-lg p-3 border border-zinc-900/50">
                                        <span className="text-[10px] text-zinc-500 uppercase tracking-wider block font-bold font-mono">Resolution Status</span>
                                        <span className="text-xs text-zinc-300 font-mono mt-1 block">{sig.status}</span>
                                      </div>
                                    </div>
                                  </div>
                                </div>
                              </td>
                            </tr>
                          )}
                        </React.Fragment>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </div>
    </div>
  );
}
